#stage 1 node version + builder
FROM node:20-alpine AS builder

# create from Workdirectory
WORKDIR /app

# copy package json. 
COPY package*.json .

# install dependencies from package json. 
RUN npm install

# copy the Projekt Code
COPY . .

# App compromise
RUN npm run build

# stage 2 
FROM nginx:alpine

# copy from builder
COPY --from=builder /app/dist/angular-conduit /usr/share/nginx/html

COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# env variable
ARG APPLICATION_PORT=80
ENV APPLICATION_PORT=${APPLICATION_PORT}
EXPOSE ${APPLICATION_PORT}


ENTRYPOINT ["/entrypoint.sh"]