# stage one: python version and builder
FROM python:3.5-slim AS builder

# create the workdirectory
WORKDIR /app

# copy requirements 
COPY requirements.txt .

# install requirements 
RUN pip install -r requirements.txt

# stage 2 
FROM python:3.5-slim

# create workdirecktory
WORKDIR /app

# copy from stage 1 install packeges und scripts
COPY --from=builder /usr/local/lib/python3.5/site-packages /usr/local/lib/python3.5/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY . .

RUN useradd -m -r appuser && chown -R appuser:appuser /app

COPY entrypoint.sh /entrypoint.sh

# make entrypoint.sh executeble
RUN chmod +x /entrypoint.sh && chown appuser:appuser /entrypoint.sh

# default port
ARG APPLICATION_PORT=8000

# env variable
ENV APPLICATION_PORT=${APPLICATION_PORT}

# default port
EXPOSE ${APPLICATION_PORT}

USER appuser

# entrypoint
CMD ["/entrypoint.sh"]