# stage 1 Python Version und  builder
FROM python:3.5-slim AS builder

# erstellen vom Workdirectory
WORKDIR /app

# requirements kopieren
COPY requirements.txt .

# requirements installieren
RUN pip install -r requirements.txt

# stage 2 
FROM python:3.5-slim

# erstellen workdirecktory
WORKDIR /app

# kopieren von stage 1 installierte pakete und scripte
COPY --from=builder /usr/local/lib/python3.5/site-packages /usr/local/lib/python3.5/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY . .

RUN useradd -m -r appuser && chown -R appuser:appuser /app

COPY entrypoint.sh /entrypoint.sh

# macht entrypoint.sh ausführbar
RUN chmod +x /entrypoint.sh && chown appuser:appuser /entrypoint.sh

# standart port
ARG APPLICATION_PORT=8000

# umgebungsvariablen
ENV APPLICATION_PORT=${APPLICATION_PORT}

# standart port
EXPOSE ${APPLICATION_PORT}

USER appuser

# entrypoint
CMD ["/entrypoint.sh"]