name: Conduit Deployment

on:
  push:
    branches:
      - Setup-docker

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        id: owner
        run: echo "owner=${OWNER,,}" >> "$GITHUB_OUTPUT"
        env:
          OWNER: ${{ github.repository_owner }}    

      - name: build & push-backend image
        uses: docker/build-push-action@v7     
        with:
          context: conduit-backend-master
          file: conduit-backend-master/dockerfile
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.owner }}/conduit-backend:latest

      - name: build & pushfrontend image
        uses: docker/build-push-action@v7 
        with:
          context: conduit-frontend-master
          file: conduit-frontend-master/dockerfile
          push: true
          tags: ghcr.io/${{ steps.owner.outputs.owner }}/conduit-frontend:latest

      - name: connect to SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd Conduit-Container
            docker compose pull
            docker compose up -d
